import { fromArray, toArray } from '../data/TreeNode'
import { deleteNode as solution } from '.'

describe(solution, () => {
  it.skip('case 1', () => {
    const root = fromArray([5, 3, 6, 2, 4, null, 7])
    const result = solution(root, 3)
    expect(toArray(result)).toEqual([5, 4, 6, 2, null, null, 7])
  })
  it.skip('case 2', () => {
    const root = fromArray([5, 3, 6, 2, 4, null, 7])
    const result = solution(root, 0)
    expect(toArray(result)).toEqual([5, 3, 6, 2, 4, null, 7])
  })
  it.skip('case 3', () => {
    const root = fromArray([])
    const result = solution(root, 0)
    expect(toArray(result)).toEqual([])
  })
  it.skip('case 4', () => {
    const root = fromArray([5, 3, 6, 2, 4, null, 7])
    const result = solution(root, 5)
    expect(toArray(result)).toEqual([6, 3, 7, 2, 4])
  })
  it.skip('case 5', () => {
    const root = fromArray([50, 30, 70, null, 40, 60, 80])
    const result = solution(root, 50)
    expect(toArray(result)).toEqual([60, 30, 70, null, 40, null, 80])
  })
  it('case 5', () => {
    const root = fromArray([
      2,
      0,
      33,
      null,
      1,
      25,
      40,
      null,
      null,
      11,
      31,
      34,
      45,
      10,
      18,
      29,
      32,
      null,
      36,
      43,
      46,
      4,
      null,
      12,
      24,
      26,
      30,
      null,
      null,
      35,
      39,
      42,
      44,
      null,
      48,
      3,
      9,
      null,
      14,
      22,
      null,
      null,
      27,
      null,
      null,
      null,
      null,
      38,
      null,
      41,
      null,
      null,
      null,
      47,
      49,
      null,
      null,
      5,
      null,
      13,
      15,
      21,
      23,
      null,
      28,
      37,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      8,
      null,
      null,
      null,
      17,
      19,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      7,
      null,
      16,
      null,
      null,
      20,
      6,
    ])
    const result = solution(root, 33)
    expect(toArray(result)).toEqual([
      2,
      0,
      34,
      null,
      1,
      25,
      40,
      null,
      null,
      11,
      31,
      35,
      45,
      10,
      18,
      29,
      32,
      null,
      36,
      43,
      46,
      4,
      null,
      12,
      24,
      26,
      30,
      null,
      null,
      null,
      39,
      42,
      44,
      null,
      48,
      3,
      9,
      null,
      14,
      22,
      null,
      null,
      27,
      null,
      null,
      38,
      null,
      41,
      null,
      null,
      null,
      47,
      49,
      null,
      null,
      5,
      null,
      13,
      15,
      21,
      23,
      null,
      28,
      37,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      8,
      null,
      null,
      null,
      17,
      19,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      7,
      null,
      16,
      null,
      null,
      20,
      6,
    ])
  })
})
