# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  rs_test:
    name: Rust Test Suite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust/leetcode-tasks
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path rust/leetcode-tasks/Cargo.toml

#   ts_test:
#     name: Typesctipt Test Suite
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: ./ts
#     steps:
#       - name: Checkout sources
#         uses: actions/checkout@v2

#       - name: Install node modules
#         run: yarn

#       - name: Run Typescript solutions tests
#         run: yarn test
